language: python

dist: xenial 

python:
  - "3.6"

before_install:
  - sudo apt-get install -y jq
  # - wget https://github.com/khaledhosny/ots/releases/download/v7.1.8/ots-7.1.8-linux.zip
  # - unzip ots-7.1.8-linux.zip
  # - sudo mv ots-7.1.8-linux/ots-sanitize /usr/local/bin/ots-sanitize

install:
  - pip install fontbakery
  - pip install Pillow
  - pip install pybrowserstack-screenshots==0.1
  - pip install git+https://github.com/m4rc1e/diffbrowsers@d76510a62f8061c5335168378b45e01328c2ae67

script:
  - python viz_pr.py
  # - sh run_fb.sh
