language: python

dist: trusty

python:
  - "3.6.1"


before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r-test -y
  - sudo apt-get update
  - sudo apt-get install gcc-7 g++-7
  - export CC=gcc-7
  - export CXX=g++-7
  - sudo apt-get install -y jq
  - sudo apt-get install -y libfreetype6-dev libglib2.0-dev libcairo2-dev
  - curl -O "https://www.freedesktop.org/software/harfbuzz/release/harfbuzz-2.3.0.tar.bz2"
  - tar -xjvf "harfbuzz-2.3.0.tar.bz2"
  - cd harfbuzz-2.3.0
  - ./configure --with-cairo=yes && make && sudo make install
  - sudo ldconfig
  - cd ..

install:
  - pip install git+https://github.com/googlefonts/gftools

script:
  - hb-view --version
  - python .ci/viz_pr.py
  - export CC=gcc-7
  - export CXX=g++-7

