language: python

dist: xenial 

python:
  - "3.7"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y jq
  - sudo apt-get install -y libfreetype6-dev libglib2.0-dev libcairo2-dev
  - curl -O "https://www.freedesktop.org/software/harfbuzz/release/harfbuzz-2.3.1.tar.bz2"
  - tar -xjvf "harfbuzz-2.3.1.tar.bz2"
  - cd harfbuzz-2.3.1
  - ./configure \
      --disable-dependency-tracking \
      --disable-gtk-doc-html \
      --with-glib=no \
      --with-cairo=yes \
      --with-icu=no \
      --enable-static \
      --disable-shared
  - make
  - make install
  - cd util
  - PATH=$(pwd):$PATH
  - cd ../..

install:
  - pip install git+https://github.com/googlefonts/gftools

script:
  - python .ci/viz_pr.py

