language: python

dist: xenial

python:
  - "3.7.1"


before_install:
        #  - sudo add-apt-repository ppa:ubuntu-toolchain-r-test -y
  - sudo apt-get update
    #- sudo apt-get install gcc-7 g++-7
    #- export CC=gcc-7
    #- export CXX=g++-7
  - sudo apt-get install -y jq
  - sudo apt-get install -y gcc g++ libfreetype6-dev libglib2.0-dev libcairo2-dev
  - curl -O "https://www.freedesktop.org/software/harfbuzz/release/harfbuzz-2.3.0.tar.bz2"
  - tar -xjvf "harfbuzz-2.3.0.tar.bz2"
  - cd harfbuzz-2.3.0
  - ./configure --with-cairo --with-icu --with-freetype && make && sudo make install
  - sudo ldconfig
  - cd ..

install:
  - pip install git+https://github.com/m4rc1e/tools@20bc01cb2fe368e356239ed56bf79ed24b1b3100

script:
  - free
  - python .ci/viz_pr.py

