language: python

dist: xenial 

python:
  - "3.6"

before_install:
  - sudo apt-get install -y jq
  - sudo apt-get install -y libfreetype6-dev libglib2.0-dev libcairo2-dev libharfbuzz-dev

install:
  - pip install fontbakery
  - pip install git+https://www.github.com/m4rc1e/tools@3c9021cce74203d2e3cc89783f0d44ae2ac9101f

script:
  - sh run_fb.sh

after_success:
  - python viz_pr.py
