language: python

dist: xenial

python:
  - "3.7.1"


before_install:
        #  - sudo add-apt-repository ppa:ubuntu-toolchain-r-test -y
  - sudo apt-get update
    #- sudo apt-get install gcc-7 g++-7
    #- export CC=gcc-7
    #- export CXX=g++-7
  - sudo apt-get install -y jq
  - sudo apt-get install -y gcc g++ libfreetype6-dev libglib2.0-dev libcairo2-dev
  - curl -O "https://www.freedesktop.org/software/harfbuzz/release/harfbuzz-2.3.0.tar.bz2"
  - tar -xjvf "harfbuzz-2.3.0.tar.bz2"
  - cd harfbuzz-2.3.0
  - ./configure --with-cairo --with-icu --with-freetype && make && sudo make install
  - sudo ldconfig
  - cd ..

install:
  - pip install git+https://github.com/m4rc1e/tools@ef405aa40b068c88ea06075b80343a89e1f7000e
  - pip uninstall fontdiffenator -y
  - pip install git+https://github.com/m4rc1e/fontdiffenator@61d6004b06226296158f1f33a2f775d2c0db01e9

script:
  - echo "hello"
  - python .ci/viz_pr.py

