language: python

dist: xenial 

python:
  - "3.6"

before_install:
  - sudo apt-get install -y jq
  - sudo apt-get install -y libfreetype6-dev libglib2.0-dev libcairo2-dev libharfbuzz-dev

install:
  - pip install fontbakery
  - pip install git+https://github.com/m4rc1e/tools@94570a0d46733167afc1b735babb79dfc238ed12

script:
  - sh run_fb.sh

after_success:
  script:
    - python viz_pr.py
