language: python

dist: xenial 

python:
  - "3.6"

before_install:
  - sudo apt-get install -y jq
  - wget https://github.com/khaledhosny/ots/releases/download/v7.1.8/ots-7.1.8-linux.zip
  - unzip ots-7.1.8-linux.zip
  - sudo mv ots-7.1.8-linux/ots-sanitize /usr/local/bin/ots-sanitize

install:
  - pip install fontbakery
  - pip install git+https://github.com/m4rc1e/diffbrowsers@a7e2602cd7e2303c75b67fc8e74c993aa4140123

# script:
#   - sh run_fb.sh

# after_success:
script:
  - python viz_pr.py
