name: "Andika"
designer: "SIL International"
license: "OFL"
category: "SANS_SERIF"
date_added: "2011-08-10"
fonts {
  name: "Andika"
  style: "normal"
  weight: 400
  filename: "Andika-Regular.ttf"
  post_script_name: "Andika"
  full_name: "Andika"
  copyright: "Copyright (c) SIL International, 2004-2014."
}
subsets: "cyrillic"
subsets: "cyrillic-ext"
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
