name: Google Fonts QA
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:

  build:
    name: Build Google Fonts
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
    
      - uses: actions/checkout@v1
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          # TODO use build matrix?
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/googlefonts/diffenator2
          pip install "gftools[qa]@git+https://github.com/m4rc1e/tools@qa-diffenator2"
          shell: bash
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
      - name: Setup Chrome Driver
        uses: nanasess/setup-chromedriver@master
      - name: Setup Firefox
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: '84.0'
      - name: Setup Firefox Driver
        uses: m4rc1e/setup-geckodriver@master
          
      - name: Check fonts
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
          SCREENSHOTS: true
        run: |
          python -m youseedee 0x078A
          chromedriver --url-base=/wd/hub &
          sh .ci/run.sh
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "out"

      - name: Upload check results
        if: steps.check_files.outputs.files_exists == 'true'
        uses: actions/upload-artifact@v1
        with:
          name: qa
          path: out/

