name: Google Fonts QA
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:

  build:
    name: Build Google Fonts
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.9]
        os: [ubuntu-latest] #[ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
    
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install packages
        run: |
          pip install git+https://github.com/m4rc1e/diffenator2
          pip install "gftools[qa]@git+https://github.com/m4rc1e/tools@qa-diffenator2"
        shell: bash
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
      - name: Setup Chrome Driver
        uses: nanasess/setup-chromedriver@master

      - name: Setup Firefox
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: '84.0'
      - name: Setup Firefox Driver
        uses: m4rc1e/setup-geckodriver@master
          
      - name: Check fonts
        run: |
          # sh .ci/run.sh
          echo "starting"
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          diffenator2 proof ofl/mavenpro/MavenPro[wght].ttf --imgs -o out
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
          SCREENSHOTS: true
          PYTHONIOENCODING: 'utf-8'
          PYTHONUTF8: '1'
        shell: bash

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "out"

      - name: Upload check results
        if: steps.check_files.outputs.files_exists == 'true'
        uses: actions/upload-artifact@v1
        with:
          name: qa
          path: out/
